import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Menu from '/components/Menu.js'

export default function Cadastrar() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BIBLIOTECA DO RAFAEL</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/561ef54e49ed9f529f00f39cd0d25461-papel-timbrado-neon-vermelho-letra-r.png" />
  
    
    </Head>
<Menu/>
    
      <main className={styles.main}>
    
      <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />

      
<div className={styles.wrapper}>
    <div className={styles.digitaçãosimples}>
     <h1 className={styles.title}>
    <p> Bem vindo ao site de</p> LOGIN
    </h1>
    </div>
    </div>


    

    
      </main>
            <footer className={styles.footer}>
    <h1>www.livrariadorafael.com</h1>
      </footer>
    </div>
  )
}
