import api from '../api/api.js'
import {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Menu from '/components/Menu.js'
import Cautor from '/components/cautor.js'

export default function CadastrarL() {
 
  return (
    <> 
    <div className={styles.container}>
      <Head>
        <title>BIBLIOTECA DO RAFAEL</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/561ef54e49ed9f529f00f39cd0d25461-papel-timbrado-neon-vermelho-letra-r.png" />
  
    
    </Head>
<Menu/>
    
      <main className={styles.main}>

  <Cautor/>
        
    
      </main>
            <footer className={styles.footer}>
    <h1>www.bibliotecadorafael.com</h1>
      </footer>
    </div>
      </>
  )
}
