import api from '../api/api.js'
import {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Menu from '/components/Menu.js'
import Cartao from '/components/cartao2.js'
import Link from 'next/link'

export default function Livros() {
  const [livros, setLivros]= useState([])
  useEffect(()=>{
    api.get('/livrosmostrar')
      .then(response=>{
        setLivros(response.data)
      })
      .catch(err => {
        console.log("Tem algo de errado" , err)
      })
  }, [])





  return (
    <div className={styles.container}>
      <Head>
        <title>BIBLIOTECA DO RAFAEL</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/561ef54e49ed9f529f00f39cd0d25461-papel-timbrado-neon-vermelho-letra-r.png" />
  
    
    </Head>
<Menu/>
    
      <main className={styles.main}>

<h1 className={styles.textocadastro}>Deseja cadastar um novo livro clique aqui:<center><br/> <i><Link href="/posts/cadastrarlivros"> "Cadastrar Livro" </Link></i></center>
                                                
</h1>
        
        
        {
       livros.map(livro => {
         return(
         <div className={styles.cards} key={livro.id}>
          <div className={styles.espacamento}>
            
           <Cartao 
             id={livro.id}
             titulo={livro.titulo} 
             editora={livro.editora}
             data_publicacao={livro.data_publicacao}
             preco={livro.preco}
             />
         </div> 
         </div>
         )
       })
      }
      <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />

        

    
      </main>
            <footer className={styles.footer}>
    <h1>www.bibliotecadorafael.com</h1>
      </footer>
    </div>
  )
}
